### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by nikibor** [NVIDIA/tensorrt-inference-server#1102]
**Description**
After call of model result, GPU-util don't work - memory allocated for request not flush. As a result, on a second request there is a Out of memory exception

**TRTIS Information**
NVIDIA Release 19.11 (build 8810908)
Client: Docker Engine - Community
 Version:          19.03.5
 API version:      1.40
 Go version:       go1.12.12
 Git commit:       633a0ea838
 Built:            Wed Nov 13 07:29:52 2019
 OS/Arch:          linux/amd64
 Experimental:     false

Server: Docker Engine - Community
 Engine:
 Version:         19.03.5
 API version:     1.40 (minimum version 1.12)
 Go version:      go1.12.12
 Git commit:      633a0ea838
 Built:           Wed Nov 13 07:28:22 2019
 OS/Arch:         linux/amd64
 Experimental:    false
 containerd:
 Version:         1.2.10
 GitCommit:       b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
 Version:         1.0.0-rc8+dev
 GitCommit:       3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
 Version:         0.18.0
 GitCommit:       fec3683

**To Reproduce**
Serve tensorflow model on separate GPU by command:

> sudo docker run --rm --gpus all --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -v '/home/meetingnotes/tensorrt/castom_ops:/castom_ops' -p 7000:8000 -p 7001:8001 -p 7002:8002 -v '/home/meetingnotes/tensorrt/model_rep:/models' -eLD_PRELOAD="/castom_ops/coref_kernels.so" 4fe0fddfcef2 trtserver --model-repository=/models

**Comment by CoderHam** [comment]
We fixed a memory leak in r20.02. Could you give us more information on the memory leak so we can verify that this is needed the same issue? 

When the model runs the first time some model specific cache is collected. This would ideally remain till the model is unloaded. 

Please provide more specific numbers such as memory free before running TRTIS, after loading the model, after first inference etc.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen with requested information.

**Comment by nikibor** [comment]
Hello. On 20.02 version, memory leak still shows, less then previous release, but still.
On TensorRt inference server launch: 
![Снимок экрана от 2020-02-27 16-06-46](https://user-images.githubusercontent.com/15349727/75447832-2c75f980-597b-11ea-8149-ca6901afc955.png)

After 1 incomming request:
![Снимок экрана от 2020-02-27 17-26-37](https://user-images.githubusercontent.com/15349727/75454346-584aac80-5986-11ea-84a7-1a2b47ea8e26.png)

TensorRt inference server message:
2020-02-27 14:23:39.848202: I tensorflow/core/common_runtime/bfc_allocator.cc:929] Stats: 
Limit:                 14240282051
InUse:                  6261097728
MaxInUse:               6567164928
NumAllocs:                    2473
MaxAllocSize:            680636416

2020-02-27 14:23:39.848259: W tensorflow/core/common_runtime/bfc_allocator.cc:424] ************************_________________________***************************************************
2020-02-27 14:23:39.848347: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at tile_ops.cc:220 : Resource exhausted: OOM when allocating tensor with shape[166171,8850] and type int32 on /job:localhost/replica:0/task:0/device:GPU:1 by allocator GPU_1_bfc

It looks like some of memory really flush, but not all. Memory leak was detected on gpu:1, from time to time, gpu:0 fails with OOM exception too

**Comment by deadeyegoodwin** [comment]
Can you simplify the failure to a single GPU? It is not clear what is running on the other GPUs or why that is relevant. It is a known "feature" of Tensorflow that it does not release GPU memory back to the system, even if you unload all TF models. See, for example, https://github.com/NVIDIA/tensorrt-inference-server/issues/1082#issuecomment-581521677.

Do you have a repro that shows the same inference request, when repeated, causes the GPU memory usage to increase over time? For example, you can use perf_client to send a large number of inference requests repeatedly to the server.

**Comment by nikibor** [comment]
Full log of process, described above
[model_inference.log](https://github.com/NVIDIA/tensorrt-inference-server/files/4266581/model_inference.log)

Also, on build 19.11-py3 Pytorch models show no leak in runtime, on latest 20.02-py3 same configuration fails on requests passed ealier.

**Comment by deadeyegoodwin** [comment]
I don't think you included the entire log, but it looks like you have both a TF and PyT model loaded. When you load a model it will use some GPU memory and then when you run the model it will use some additional GPU memory. How much in each case depends on the framework. For example, with TensorRT, all GPU memory will be allocated at load time and no additional GPU memory is required when handling an inference request. For TF/PyT some GPU memory will be used at load time but most GPU memory will be allocated when handling an inference request. 

You seem to be sending a TF request that is failing. You can see from the log that TF thinks it has 5649298883 bytes available to it:

total_region_allocated_bytes_: 8590983168 memory_limit_: 14240282051 available bytes: 5649298883 curr_region_allocation_bytes_: 8589934592

But the inference request needs 5929783296 (for the [166171,8850] int32 tensor):

2020-02-28 10:25:16.811985: W tensorflow/core/common_runtime/bfc_allocator.cc:419] Allocator (GPU_1_bfc) ran out of memory trying to allocate 5.52GiB (rounded to 5929783296).  Current allocation summary follows.

As to why this worked in 19.11... 20.02 has added features that may be using more memory and the TF and PyT versions are also updated and they may be using more memory as well. One thing to try is to disable the pinned-memory pool in TRTIS since that allocates a largish chunk of GPU memory. Use --pinned-memory-pool-byte-size=0
